/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Wolf (https://sketchfab.com/wolfmic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/red-button-e7685cccf7364682bc6a7883d0b8c503
title: Red Button
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";
import { useSDK } from "@thirdweb-dev/react";
import { userMintNFT } from "../../../../web3/thirdweb";
export function MintNFT(props) {
  const { user } = props;
  const { nodes, materials } = useGLTF("/red_button.glb");
  const meshRef = useRef();
  const [cubeRef] = useBox(() => ({
    mass: 1000,
    args: [1, 1, 1],
    material: {
      friction: 5,
    },
    type: "Kinematic",
    ...props,
  }));
  const sdk = useSDK();
  async function mintANFT() {
    await userMintNFT(sdk);
  }
  return (
    <group dispose={null} ref={cubeRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.23}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            ref={meshRef}
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Material}
            onClick={mintANFT}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/red_button.glb");
